routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('', function () {
    return view('pages.first.create');
});


Route::group(['middleware'=>['guest']],function(){
	
	Route::post('/login',[
		'as'=>'auth.login',
		'uses'=>'LoginController@postLogin']);
	
	Route::get('traveller/register','RegisterController@getRegister');

	Route::post('{role}/register',[
		'as'=>'auth.register',
		'uses'=>'RegisterController@postRegister'
		]);

	Route::get('{role}/sendotp/register','OtpController@sendMessage');

	Route::post('{role}/verifyOtp/register',[
		'as'=>'verifyotp',
		'uses'=>'OtpController@verifyOtp'
		]);
});

Route::get('logout','LoginController@logout');

Route::group(['middleware'=>'auth'],function() 
{
	Route::resource('tickets','TicketController');
});
Route::get('/toll-plazas-on-map',function(){
	return view('pages.toll-plazas-on-map');
});

Route::get('/toll-plazas-at-glance',function(){
	return view('pages.toll-plazas-at-glance');
});
Route::get('/trip',function(){
	return view('pages.trip');
});
Route::get('/feedback',function(){
	return view('pages.feedback');
});
Route::get('/complain',function(){
	return view('pages.complain');
});
//Route::get('/contact-us',function(){
//	return view('pages.contact-us');
//});


Route::get('/Vehicle-details',function(){
	return view('pages.Vehicle-details');
});
Route::get('/Previous-trip',function(){
	return view('pages.Previous-trip');
});
Route::get('/New-Trip',function(){
	return view('pages.New-Trip');
});

Route::resource('contactus','ContactController');

resources/views/layout/footer.blade.php
<footer id="footer">

    <div class="info-line">
            <div class="container_12">
            <div class="clear"></div>
            </div>
    </div>
        <div class="contentborder">
           <img id="contentborder">
         </div>

    <div class="container_12 main-footer">

            <div>
                <div class="inner" style="text-align: center;">
                    <h3 class="rs common-title">Menu</h3>

                    <ul class="rs">
                        <a href="">Home</a> |
                        <a href="{{URL::asset('/toll-plazas-on-map')}}"">View Toll Plazas On Map</a> |
                        <a href="{{URL::asset('/toll-plazas-at-glance')}}">List of Toll Plazas</a> |
                        <a href="#">User Guildeline</a> |
                        <a href="{{URL::asset('/feedback')}}">Feedback</a> |
                        <a href="{{URL::asset('/contact-us')}}">Contact us</a>
            
                    </ul>
                </div>
            </div><!--end: .foot-menu -->
            <div class="clear"></div>
            <div class="lst-btn-social clearfix">
            </div>
            <p class="rs copyright"><span class="lbl">Developed by </span> <a href="" class="val" title="Toll Project company" target="_blank">5F Group.</a></p>
        </div>
</footer><!--end: #footer -->

resources/views/layout/nav.blade.php
    <span class="top-line"></span>
        <div class="container_12">
            <div class="top-login-reg">
            @if(!Auth::user())
                <a id="myBtn" href="#">Login</a>
                <a href="{{URL::asset('traveller/register')}}">Register</a>
            @else
                <a href="{{URL::asset('logout')}}">Logout</a>
            @endif
            </div>
            <div class="clear"></div>
            <div class="head-menu clearfix">
                <h1 id="logo">
                    <a href="{{URL::asset('')}}">
                        <img src="public/images/Latest Logo1.png">
                    </a>
                </h1>
                <nav class="main-nav">
                    <ul id="main-menu" class="nav nav-horizontal">
                        <li class="active">
                            <a href="{{URL::asset('')}}">Home</a>
                        </li>
                        <li>
                            <a href="{{URL::asset('/toll-plazas-on-map')}}">Toll Plazas On Map</a>
                        </li>
                        <li>
                            <a href="{{URL::asset('/toll-plazas-at-glance')}}">Toll Plazas At Glance</a>
                        </li>
                        <li class="has-sub">
                            <a href="">Trip</a>
                            <ul class="sub-menu">
                            <li><a href="{{URL::asset('/New-Trip')}}">New Trip</a></li>
                            <li><a href="{{URL::asset('/Vehicle-details')}}">Vehicle Details</a></li>
                                <li><a href="{{URL::asset('/Previous-trip')}}">Previous Trip</a></li>
                            </ul>
                        </li>
                          <li class="has-sub">
                            <a href="">User Help</a>
                            <ul class="sub-menu">
                                <li><a href="#">User Manual</a></li>
                                <li><a href="{{URL::asset('/feedback')}}">Feedback</a></li>
                                <li><a href="{{URL::asset('/complain')}}">Complain</a></li>
                            </ul>
                        </li>
                        <li><a href="{{route('contactus.index')}}">Contact Us</a>
                        </li>
                      
                    </ul>
                    <a id="btn-toogle-menu" class="btn-toogle-menu" href="#alternate-menu">
                        <span class="line-bar"></span>
                        <span class="line-bar"></span>
                        <span class="line-bar"></span>
                    </a>
                    <div id="right-menu">
                        <ul class="alternate-menu">
                            <li><a href="">Home</a></li>

                            <li><a href="{{URL::asset('/toll-plazas-on-map')}}">Toll Plazas On Map</a></li>

                            <li><a href="{{URL::asset('/toll-plazas-at-glance')}}">Toll Plazas At Glance</a></li>

                            <li class="has-sub"><a href="">Trip</a>
                            <ul class="sub-menu">
                            <li><a href="{{URL::asset('/New-Trip')}}">New Trip</a></li>
                            <li><a href="{{URL::asset('/Vehicle-details')}}">Vehicle Details</a></li>
                                <li><a href="{{URL::asset('/Previous-trip')}}">Previous Trip</a></li>
                            </ul>
                            </li>

                            <li class="has-sub">
                            <a href="">User Help</a>
                            <ul class="sub-menu">
                                <li><a href="#">User Manual</a></li>
                                <li><a href="{{URL::asset('/feedback')}}">Feedback</a></li>
                                <li><a href="{{URL::asset('/complain')}}">Complain</a></li>
                            </ul>
                        </li>
                            <li><a href="{{URL::asset('/contact-us')}}">Contact Us</a></li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
        
        <div class="contentborder">
           <img id="contentborder">
        </div>
     
         <!--   <div class="sequence-theme">
                <div id="sequence">
                    <div class="wrap-pagination">          
                    </div>
                </div>
            </div>-->
          

resources/views/layout/slidebar.blade.php
<div class="head-about-us container_12 clearfix ">
    <div class="grid_12 content-about clearfix">
        <div id="jssor_1" class="slide-main">
        <!-- Loading Screen -->
            <div data-u="slides" class="slide-img">
        
                <div data-p="225.00">
                    <img data-u="image" src="public/images/t1.jpg" />
                 </div> 
                <div data-p="225.00">
                    <img data-u="image" src="public/images/t2.jpg" />
                </div>
                <div data-p="225.00" data-po="80% 55%" style="display:none;">
                    <img data-u="image" src="public/images/t3.jpg" />
                </div>
                <div data-p="225.00">
                    <img data-u="image" src="public/images/t4.jpg" />
                </div> 
                <div data-p="225.00" style="display:none;">
                    <img data-u="image" src="public/images/t5.jpg" />
                </div>
                <div data-p="225.00" data-po="80% 55%" style="display:none;">
                    <img data-u="image" src="public/images/t6.jpg" />
                </div>
                <div data-p="225.00" data-po="80% 55%" style="display:none;">
                    <img data-u="image" src="public/images/t7.jpg" />
                </div>
            </div>
        <!-- Bullet Navigator -->
            <div data-u="navigator" class="jssorb05 slide-bullet"  data-autocenter="1">
                <!-- bullet navigator item prototype -->
                <div data-u="prototype" style="width:16px;height:16px;"></div>
            </div>
        </div>
        <script type="text/javascript">jssor_1_slider_init();</script>
    </div>
</div>       
<!--<div class="top-slide">
    <div class="sequence-theme">
        <div id="sequence">
            <div class="wrap-pagination">          
            </div>
        </div>
    </div>
</div>  -->