routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('', function () {
    return view('pages.first.create');
});


Route::group(['middleware'=>['guest']],function(){
	
	Route::post('/login',[
		'as'=>'auth.login',
		'uses'=>'LoginController@postLogin']);
	
	Route::get('traveller/register','RegisterController@getRegister');

	Route::post('{role}/register',[
		'as'=>'auth.register',
		'uses'=>'RegisterController@postRegister'
		]);

	Route::get('{role}/sendotp/register','OtpController@sendMessage');

	Route::post('{role}/verifyOtp/register',[
		'as'=>'verifyotp',
		'uses'=>'OtpController@verifyOtp'
		]);
});

Route::get('logout','LoginController@logout');

Route::group(['middleware'=>'auth'],function() 
{
	Route::resource('tickets','TicketController');
});
Route::get('/toll-plazas-on-map',function(){
	return view('pages.toll-plazas-on-map');
});

Route::get('/toll-plazas-at-glance',function(){
	return view('pages.toll-plazas-at-glance');
});
Route::get('/trip',function(){
	return view('pages.trip');
});
Route::get('/feedback',function(){
	return view('pages.feedback');
});
Route::get('/complain',function(){
	return view('pages.complain');
});
//Route::get('/contact-us',function(){
//	return view('pages.contact-us');
//});


Route::get('/Vehicle-details',function(){
	return view('pages.Vehicle-details');
});
Route::get('/Previous-trip',function(){
	return view('pages.Previous-trip');
});
Route::get('/New-Trip',function(){
	return view('pages.New-Trip');
});

Route::resource('contactus','ContactController');

resources/views/pages/New-Trip.blade.php
@extends('pages.index')
<?php $title = "New Trip"; ?>

@section('page-content')

	<div class="container">
		<h1 align="center">This is page under construction </h1>
		<h2 align="center">OR</h2>
		<h2 align="center">This page under maintaince</h2>
		<h2 align="center">Please try after sometimes</h2>
	</div>





@include('pages.auth.login')	
@endsection

resources/views/pages/Previous-trip.blade.php
@extends('pages.index')
<?php $title = "Previous Trip"; ?>

@section('page-content')

	<div class="container">
		<h1 align="center">This is page under construction </h1>
		<h2 align="center">OR</h2>
		<h2 align="center">This page under maintaince</h2>
		<h2 align="center">Please try after sometimes</h2>
	</div>





@include('pages.auth.login')	
@endsection

resources/views/pages/Vehicle-details.blade.php
@extends('pages.index')
<?php $title = "Vehicle Detalis"; ?>

@section('page-content')

	<div class="container">
		<h1 align="center">This is page under construction </h1>
		<h2 align="center">OR</h2>
		<h2 align="center">This page under maintaince</h2>
		<h2 align="center">Please try after sometimes</h2>
	</div>





@include('pages.auth.login')	
@endsection

resources/views/pages/complain.blade.php
@extends('pages.index')
<?php $title = "Complain"; ?>

@section('page-content')

	<div class="container">
		<h1 align="center">This is page under construction </h1>
		<h2 align="center">OR</h2>
		<h2 align="center">This page under maintaince</h2>
		<h2 align="center">Please try after sometimes</h2>
		
	</div>





@include('pages.auth.login')	
@endsection

resources/views/pages/contact-us.blade.php
@extends('pages.index')
<?php $title = "Contact Us"; ?>
@section('page-content')

	<!--<div class="container">
		<h1 align="center">This is page under construction </h1>
		<h2 align="center">Please try after sometimes</h2>
	</div> -->
	<div class="layout-2cols sidebar-right clearfix contact-us-page">
        <div class="content grid_8">
            <div class="wrap-contact-form">
                <div class="common-title mr-grid">Contact Form</div>

                <div class="clearfix form contact-form">
                   <form id="contact-form" class="sky-form" action="{{route('contactus.store')}}" method="post">
                       {{csrf_field()}}
                   <fieldset>
                       <div class="grid_6">
                           <label class="lbl-wrap" for="txt-name">
                               <input id="txt-name" class="txt" type="text" name="name" placeholder="Name" />
                           </label>
                       </div>
                       <div class="grid_6">
                           <label class="lbl-wrap" for="txt-email-address">
                               <input id="txt-email-address" class="txt" type="email" name="email" placeholder="Email Address"/>
                           </label>
                       </div>
                       <div class="grid_6">
                           <label class="lbl-wrap" for="txt-phone">
                               <input id="txt-phone" maxlength="10" class="txt" type="text" name="phone" placeholder="Phone"/>
                           </label>
                       </div>
                       <div class="grid_6">
                           <label class="lbl-wrap" for="txt-website">
                               <input id="txt-website" class="txt" type="text" name="website" placeholder="Website"/>
                           </label>
                       </div>
                       <div class="grid_12">
                           <label class="lbl-wrap" for="txt-message">
                               <textarea class="txt" id="txt-message" cols="30" rows="10" name="message" placeholder="Message"></textarea>
                           </label>
                       </div>
                       <div class="grid_12">
                           <p class="rs ta-r clearfix">
                               <span id="response"></span>
                               <input type="submit" id="submit-contact" class="btn-blue smaller" value="Submit"/>
                           </p>
                       </div>
                       </fieldset>
                   </form>
                </div>
            </div>
        </div>
        <div class="sidebar grid_4">
            <div class="wrap-our-information">
                <div class="our-information lh-heigher">
                    <p class="rs info-item">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis.</p>
                    <p class="rs info-item">
                        <span class="fw-b">Address:</span> 111 lorem St. 5th Floor,<br />
                        Ipsum City, MA 00001
                    </p>
                    <p class="rs info-item">
                        <span class="fw-b">Phone:</span> +1 (555) 55-55-555<br />
                        (9AM - 6PM EST)
                    </p>
                    <p class="rs info-item"><span class="fw-b">Email:</span> <a class="fc-blue" href="http://envato.megadrupal.com/cdn-cgi/l/email-protection#d9aab8b5bcaa99bbbcaaadaebcbbaab6bfadf7bab6b4"><span class="__cf_email__" data-cfemail="1764767b72645775726463607275647871633974787a">[email&#160;protected]</span><script data-cfhash='f9e31' type="text/javascript">/* <![CDATA[ */!function(t,e,r,n,c,a,p){try{t=document.currentScript||function(){for(t=document.getElementsByTagName('script'),e=t.length;e--;)if(t[e].getAttribute('data-cfhash'))return t[e]}();if(t&&(c=t.previousSibling)){p=t.parentNode;if(a=c.getAttribute('data-cfemail')){for(e='',r='0x'+a.substr(0,2)|0,n=2;a.length-n;n+=2)e+='%'+('0'+('0x'+a.substr(n,2)^r).toString(16)).slice(-2);p.replaceChild(document.createTextNode(decodeURIComponent(e)),c)}p.removeChild(t)}}catch(u){}}()/* ]]> */</script></a></p>
                </div>
            </div>
        </div>
    </div>




@include('pages.auth.login')	
@endsection

resources/views/pages/feedback.blade.php
@extends('pages.index')
<?php $title = "Feedback"; ?>

@section('page-content')

	<div class="container">
		<h1 align="center">This is page under construction </h1>
		<h2 align="center">OR</h2>
		<h2 align="center">This page under maintaince</h2>
		<h2 align="center">Please try after sometimes</h2>
	</div>





@include('pages.auth.login')	
@endsection

resources/views/pages/index.blade.php
@extends('master.master')

@section('style')
	<link rel="stylesheet" href="{{asset('public/css/sky-forms.css')}}">
	<link rel="stylesheet" href="{{asset('public/css/self.css')}}">

@endsection

@section('content')
<div id="wrapper">  
	<header id="header">
		@include('layout.nav')
		@include('layout.header')
	</header>
	@yield('page-content')	
	   
	@include('layout.footer')
</div>
@endsection

@section('scripts')
	<script src="https://maps.googleapis.com/maps/api/js?signed_in=true&callback=initMap&key=" async defer></script> 
	<script type="text/javascript" src="{{asset('public/js/bootstrap.min.js')}}"></script>
	<script type="text/javascript" src="{{asset('public/js/main.js')}}"></script>
@endsection

resources/views/pages/toll-plazas-at-glance.blade.php
@extends('pages.index')
<?php $title = "Toll Plazas At Glance"; ?>

@section('page-content')

	<!--<div class="container">
		<h1 align="center">This is page under construction </h1>
		<h2 align="center">OR</h2>
		<h2 align="center">This page under maintaince</h2>
		<h2 align="center">Please try after sometimes</h2>
	</div>-->
<div class="container">
	<div class="row">
		<div class="col-sm-12">
  			<div class="body body-s src-dest">
    			<form class="sky-form">
                        
      			<fieldset>
      			   <div class="row">
                           <h3 style="text-align: center; font-style: bold">Toll Plazas List</h3><br>

                        <div class="body body-s src-dest">
                        <form class="sky-form" method="post">

                                 
                        <table style="width: 100%;">
      				<tr>
      				 <th>Sr No.</th>
                               <th>State</th>
      				 <th>Toll Plazas Name</th>
                               <th>NH-No.</th>
      				 <th>Toll Plaza Location</th>
      				 <th>Section/Stretch</th>
      				</tr>    		
                              <tr>
      				  <td>1</td>
      				  <td><a href="">Bhavnagar-Ahemdabad highway</a></td>
      				  <td>200 km</td>
      				  <td>Bhavnagar</td>
      				</tr>
      				<tr>
      				  <td>2</td>
      				  <td><a href="">Bhavnagar-Rajkot highway</a></td>
      				  <td>224 km</td>
      				  <td>Rajkot</td>
      			      </tr>
      			   </table>
				   </div>
			      </fieldset>
                        	
			</form>
			</div>
		</div>			
	</div>
</div>		




@include('pages.auth.login')	
@endsection

resources/views/pages/toll-plazas-on-map.blade.php
@extends('pages.index')
<?php $title = "Toll Plazas on map"; ?>
@section('page-content')
<div class="container">
<div class="row">
<div class="col-sm-4">
  <div class="body body-s src-dest">
    <form class="sky-form">
      <fieldset>
        <section>
          <div class="row">
            <label class="label col col-3">Source</label>
            <div class="col col-8">
              <label class="select">
                <select  name="source" id="Source">
                  <option value="Bhavnagar, in">Bhavnagar</option>  
                  <option value="Mumbai, in">Mumbai</option>   
                  <option value="Kolkata, in">Kolkata</option>    
                  <option value="Chennai, in">Chennai</option>    
                  <option value="Indore, in">Indore</option>    
                  <option value="Hyderabad, in">Hyderabad</option>    
                  <option value="Ahemdabad, in">Ahemdabad</option>    
                  <option value="Pune, in">Pune</option>    
                  <option value="Bhopal, in">Bhopal</option>    
                  <option value="Jaipur, in">Jaipur</option>    
                  <option value="Bengluru, in">Bengluru</option>    
                </select>
                <i></i>
              </label>
            </div> 
          </div> 
        </section>
        <section >
          <div class="row">
            <label class="label col col-3">Destination</label>
            <div class="col col-8">
              <label class="select">
                <select  name="destination" id="Destination">
                  <option value="Mumbai, in">Mumbai</option>    
                  <option value="New Delhi, in">New Delhi</option>    
                  <option value="Kolkata, in">Kolkata</option>    
                  <option value="Chennai, in">Chennai</option>    
                  <option value="Indore, in">Indore</option>    
                  <option value="Ahemdabad, in">Ahemdabad</option>    
                  <option value="Jaipur, in">Jaipur</option>    
                  <option value="Bengluru, in">Bengluru</option> 
                  <option value="Hyderabad, in">Hyderabad</option>    
                  <option value="Pune, in">Pune</option>    
                  <option value="Bhopal, in">Bhopal</option>      
                </select>
                <i></i>
              </label >
            </div>
          </div>
        </section>
        <section>
          <div class="row">
          <div class="col-sm-12 find">
            <label>
              <button type="button" id="search-btn" class="button serch-btn">Find Your Way</button>
            </label>
            </div>
          </div>
        </section>
      </fieldset>
    </form>
  </div>
  <div class="sky-form src-dest">
      <fieldset>
        <section>
          <div class="row">
            <label class="label col col-3">Source</label>
            <div class="col col-8">
            sdjhfkdsafjh
            </div>
          </div>
        </section>
        <section>
          <div class="row">
            <label class="label col col-3">Source</label>
            <div class="col col-8">
            sdjhfkdsafjh
            </div>
          </div>
        </section>
        <section>
          <div class="row">
            <label class="label col col-3">Source</label>
            <div class="col col-8">
            sdjhfkdsafjh
            </div>
          </div>
        </section>
      </fieldset>
</div>
</div>
<div class="col-sm-8" >
     <div id="map"></div>
</div>
</div> 
</div>


<!-- 	<div id="panel">    
    <b>Source: </b>    
    <select id="Source">    
        
       
    </select>    
    <b>Destination: </b>    
    <select id="Destination">    
           
    </select>    
    </div>     -->
   
	@include('pages.auth.login')	
@endsection